@IdentityService_HostAddress = http://localhost:5047

GET {{IdentityService_HostAddress}}/weatherforecast/
Accept: application/json

###
### Login
POST {{IdentityService_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "admin@wcc.com",
  "password": "Admin123*"
}
### Refresh
POST {{IdentityService_HostAddress}}/api/auth/refresh
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "Yw9i+CEo3eWoLpwKJSH9Wfx1KpLdOS/sWgRBsox2jNfvehOeF/hvCQ4Q7z4o4s8zGJJeVK8sm98cJ4P+2+fPMg=="
}
