@Portafolio.Api_HostAddress = http://localhost:5170
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..QGt683tqTaeUx5Iyc1b-Npif8g6V0DPVlZeMo4Uqpgs
@profileId = 1ffaacf2-615e-4632-db06-08de795b23ea

### Health check de API (sin auth)
GET {{Portafolio.Api_HostAddress}}/healthz
Accept: application/json

### 1) Crear Portfolio Profile (requiere rol Admin: portfolio.write)
POST {{Portafolio.Api_HostAddress}}/api/PortfolioProfiles
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "Harold Martin Bermu52",
  "headline": "Fullstack .NET | Microservices | Azure",
  "summary": "Perfil de portafolio para mostrar proyectos, experiencia y stack.",
  "location": "Bogota, Colombia",
  "publicEmail": "harold@email.com"
}

### 2) Obtener Portfolio Profile por Id (requiere rol Admin o User: portfolio.read)
GET {{Portafolio.Api_HostAddress}}/api/PortfolioProfiles/{{profileId}}
Authorization: Bearer {{accessToken}}
Accept: application/json

### 3) Actualizar Portfolio Profile (requiere rol Admin: portfolio.write)
PUT {{Portafolio.Api_HostAddress}}/api/PortfolioProfiles/{{profileId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "Harold Martin Bermudez",
  "headline": ".NET Backend Developer",
  "summary": "Desarrollador especializado en APIs REST con .NET y Azure.",
  "location": "Bogota, Colombia",
  "publicEmail": "harold@email.com",
  "photoUrl": "https://miportafolio.com/photo.jpg",
  "resumeUrl": "https://miportafolio.com/cv.pdf"
}

### 4) Prueba de seguridad (espera 401 sin token)
GET {{Portafolio.Api_HostAddress}}/api/PortfolioProfiles/{{profileId}}
Accept: application/json
